"""
Generate every figure and LaTeX table used in the paper, straight from the
result JSONs, into ../results/paper_assets/ with self-describing names:

  fig_synthetic_granularity_vs_eps.pdf/.png   (paper fig:synthetic-grid)
      Improvement over Hay vs epsilon, one facet per signal class, one curve
      per granularity. Source: synthetic_data_results/results.json.
  fig_ddhca_envelope.pdf/.png                 (optional companion to tab:ddhca)
      Same quantity on the five DDHC-A groups (Level per group; Node per group).
  tab_ddhca_improvement.tex                   (paper tab:ddhca)
      Improvement over Hay (%), groups x epsilons, Level and Node rows,
      plus the PL94 P1 high-SNR control row.
  tab_stratified_main.tex                     (paper tab:stratified)
      Present/empty-cell MSE for Hay/Level/Node, two representative groups
      at four epsilons. Source: census_ddhca_results/stratified_results.json.
  tab_stratified_full.tex                     (appendix version: all groups/eps)
  tab_diagnostic_validation.tex               (paper Section sec:diagnostic)
      Accuracy/regret of the penalized three-way rule (and the two-way
      ablation) on tuning vs held-out splits. Source: diagnostic_validation.json.

Regenerate everything with:  python make_paper_assets.py     (from core/)
No experiment is re-run; this script only reads the archived results.
"""
from __future__ import annotations
import json
import os
from collections import defaultdict

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

SYN_FILE = "../results/synthetic_data_results/results.json"
DDHCA_DIR = "../results/census_ddhca_results"
STRAT_FILE = os.path.join(DDHCA_DIR, "stratified_results.json")
DIAG_FILE = "../results/diagnostic_validation.json"
P1_CANDIDATES = ["../results/P1_census_results/P1_census_results.json",
                 "../results/census_results/census_results.json"]
OUT_DIR = "../results/paper_assets"

# granularity -> (name in result files, display label, color, linestyle)
GRANS = [
    ("Scalar",  "Scalar",     "#009E73", ":"),
    ("Ours",    "Level-wise", "#0072B2", "-"),
    ("PerNode", "Per-node",   "#D55E00", "--"),
]
SIGNAL_ORDER = ["uniform", "smooth", "random", "sparse"]
EPS_ORDER = [0.01, 0.1, 0.5, 1.0, 2.0, 5.0, 10.0]

plt.rcParams.update({
    "font.size": 9, "axes.titlesize": 9, "axes.labelsize": 9,
    "legend.fontsize": 8, "xtick.labelsize": 8, "ytick.labelsize": 8,
    "figure.dpi": 110, "savefig.bbox": "tight",
})


def _save(fig, stem):
    for ext in ("pdf", "png"):
        fig.savefig(os.path.join(OUT_DIR, f"{stem}.{ext}"),
                    dpi=220 if ext == "png" else None)
    plt.close(fig)
    print(f"  wrote {stem}.pdf/.png")


def fmt_mse(v: float) -> str:
    if v >= 1000:
        return f"{v:,.0f}"
    if v >= 10:
        return f"{v:.1f}"
    return f"{v:.2f}"


def fmt_pct(v: float) -> str:
    """One-decimal percentage, avoiding the ugly '-0.0'."""
    return "0.0" if abs(v) < 0.05 else f"{v:.1f}"


def _fig_wrapper(stem: str, caption: str, label: str, description: str) -> None:
    """Emit a ready-to-\\input figure environment for a generated PDF.
    Assumes \\graphicspath{{<...>/paper_assets/}} in the paper preamble.
    \\Description is the ACM accessibility alt-text (required by acmart)."""
    lines = [
        "% Auto-generated by make_paper_assets.py -- do not edit by hand.",
        r"\begin{figure*}[t]",
        r"\centering",
        rf"\includegraphics[width=\textwidth]{{{stem}.pdf}}",
        rf"\Description{{{description}}}",
        rf"\caption{{{caption}}}",
        rf"\label{{{label}}}",
        r"\end{figure*}",
    ]
    with open(os.path.join(OUT_DIR, stem + ".tex"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  wrote {stem}.tex")


# ---------------------------------------------------------------- synthetic
def fig_synthetic():
    with open(SYN_FILE) as f:
        results = json.load(f)["results"]
    # mean improvement over Hay per (signal, eps, method), across trees & scales
    agg = defaultdict(list)
    for r in results:
        for key, *_ in GRANS:
            agg[(r["signal_type"], r["epsilon"], key)].append(
                r["methods"][key]["improve_over_hay_pct"])

    fig, axes = plt.subplots(2, 2, figsize=(7.0, 4.6), sharex=True, sharey=True)
    for ax, st in zip(axes.flat, SIGNAL_ORDER):
        for key, label, color, ls in GRANS:
            y = [np.mean(agg[(st, e, key)]) for e in EPS_ORDER]
            ax.plot(EPS_ORDER, y, ls, color=color, marker="o", ms=3.5,
                    label=label)
        ax.axhline(0, color="0.6", lw=0.8)
        ax.set_xscale("log")
        ax.set_title(f"{st} signals")
        ax.set_ylim(-15, 100)
        ax.grid(True, which="both", alpha=0.25, lw=0.4)
    for ax in axes[1]:
        ax.set_xlabel(r"privacy budget $\varepsilon$")
    for ax in axes[:, 0]:
        ax.set_ylabel("improvement over Hay (%)")
    axes[0, 0].legend(loc="lower left", frameon=False)
    _save(fig, "fig_synthetic_granularity_vs_eps")
    _fig_wrapper(
        "fig_synthetic_granularity_vs_eps",
        r"Improvement in per-cell MSE over consistency projection vs.\ "
        r"privacy budget, by signal class (mean over 9 trees $\times$ 2 "
        r"scales, 50 trials per point). Level-wise shrinkage dominates on "
        r"dense, homogeneous signals; per-node overtakes on sparse and "
        r"random signals as $\varepsilon$ grows.",
        "fig:synthetic-grid",
        "Four line charts, one per signal class, showing improvement over "
        "the Hay baseline versus privacy budget for scalar, level-wise, and "
        "per-node shrinkage. Level-wise is highest on uniform and smooth "
        "signals at all budgets; on random and sparse signals the per-node "
        "curve crosses above level-wise as the budget grows.")


# ------------------------------------------------------------------ DDHC-A
def _load_ddhca():
    groups = []
    for fn in sorted(os.listdir(DDHCA_DIR)):
        if fn.startswith("ddhca_results_pop") and fn.endswith(".json"):
            with open(os.path.join(DDHCA_DIR, fn)) as f:
                groups.append(json.load(f))
    # sort sparsest first (by total population implied via config label order)
    order = {"1190": 0, "1016": 1, "2031": 2, "3657": 3, "1009": 4}
    groups.sort(key=lambda g: order.get(g["config"]["popgroup"], 99))
    return groups


def _short_label(label: str) -> str:
    return label.replace(" alone or in any combination", " (comb.)") \
                .replace(" alone", "")


def fig_ddhca(groups):
    fig, axes = plt.subplots(1, 2, figsize=(7.0, 2.8), sharey=True)
    cmap = plt.cm.viridis(np.linspace(0.15, 0.85, len(groups)))
    for ax, key, title in [(axes[0], "Ours", "Level-wise"),
                           (axes[1], "PerNode", "Per-node")]:
        for g, color in zip(groups, cmap):
            eps = [r["epsilon"] for r in g["results"]]
            y = [r["methods"][key]["improve_over_hay_pct"] for r in g["results"]]
            ax.plot(eps, y, "-o", ms=3, color=color,
                    label=_short_label(g["config"]["popgroup_label"]))
        ax.axhline(0, color="0.6", lw=0.8)
        ax.set_xscale("log")
        ax.set_title(f"{title} shrinkage")
        ax.set_xlabel(r"privacy budget $\varepsilon$")
        ax.grid(True, which="both", alpha=0.25, lw=0.4)
    axes[0].set_ylabel("improvement over Hay (%)")
    axes[0].legend(frameon=False, fontsize=7, loc="lower left",
                   title="DHC-A population group", title_fontsize=7)
    _save(fig, "fig_ddhca_envelope")
    _fig_wrapper(
        "fig_ddhca_envelope",
        r"Improvement over consistency projection on the five Detailed "
        r"DHC-A groups, sparsest (dark) to densest (light). Level-wise "
        r"gains decay with $\varepsilon$ and group density; per-node holds "
        r"a stable $51$--$53\%$ at every $\varepsilon$ and group.",
        "fig:ddhca-envelope",
        "Two line charts of improvement over the Hay baseline versus privacy "
        "budget for five census population groups. Left, level-wise "
        "shrinkage: gains start near 100 percent at the smallest budget and "
        "decay to zero, earlier for denser groups. Right, per-node "
        "shrinkage: all five curves are flat at roughly 52 percent.")


def tab_ddhca(groups):
    p1 = None
    for cand in P1_CANDIDATES:
        if os.path.exists(cand):
            with open(cand) as f:
                p1 = json.load(f)
            break
    # paired-improvement SEs live in the evaluation-suite output
    ddhca_se, p1_se = {}, None
    if os.path.exists(STRAT_FILE):
        with open(STRAT_FILE) as f:
            strat = json.load(f)
        for r in strat["results"]:
            ddhca_se[(r["popgroup"], r["epsilon"])] = r["methods"]
        p1_se = strat.get("p1_improvement_se")
    else:
        print("  !! stratified_results.json not found; Table 1 without error bars")

    def cell(point, se):
        s = fmt_pct(point)
        if se is not None:
            s += rf"\,{{\scriptsize$\pm${se:.1f}}}"
        return s

    lines = [
        "% Auto-generated by make_paper_assets.py -- do not edit by hand.",
        "% Improvement over Hay (%), per group and epsilon. Paper tab:ddhca.",
        r"\begin{table*}[t]",
        r"\centering\small",
        r"\setlength{\tabcolsep}{4pt}",
        r"\caption{Improvement in per-cell MSE over consistency projection"
        r" (\%). Groups ordered sparsest to densest; PL94 total population is"
        r" the high-SNR control. $\pm$ is the standard error, over the 50"
        r" draws, of the per-draw paired improvement.}",
        r"\label{tab:ddhca}",
        r"\begin{tabular}{llrrrrrrr}",
        r"\toprule",
        r"Release & Granularity & " +
        " & ".join(rf"$\varepsilon{{=}}{e:g}$" for e in EPS_ORDER) + r" \\",
        r"\midrule",
    ]
    # (published-results key, display label, evaluation-suite key)
    ROWS = [("Scalar", "Scalar", "Scalar"), ("Ours", "Level", "Level"),
            ("PerNode", "Node", "Node")]
    for g in groups:
        pg = g["config"]["popgroup"]
        label = _short_label(g["config"]["popgroup_label"])
        per_eps = {r["epsilon"]: r["methods"] for r in g["results"]}
        for i, (key, disp, loc) in enumerate(ROWS):
            vals = " & ".join(
                cell(per_eps[e][key]["improve_over_hay_pct"],
                     ddhca_se.get((pg, e), {}).get(loc, {}).get("imp_se"))
                for e in EPS_ORDER)
            head = label if i == 0 else ""
            lines.append(rf"{head} & {disp} & {vals} \\")
        lines.append(r"\addlinespace[2pt]")
    if p1 is not None:
        per_eps = {r["epsilon"]: r["methods"] for r in p1["results"]}
        for i, (key, disp, loc) in enumerate(ROWS):
            vals = " & ".join(
                cell(per_eps[e][key]["improve_over_hay_pct"],
                     (p1_se or {}).get(str(e), {}).get(loc, {}).get("imp_se"))
                for e in EPS_ORDER)
            head = "PL94 P1 (control)" if i == 0 else ""
            lines.append(rf"{head} & {disp} & {vals} \\")
    else:
        print("  !! P1 results not found; control row omitted")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
    path = os.path.join(OUT_DIR, "tab_ddhca_improvement.tex")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("  wrote tab_ddhca_improvement.tex")


# -------------------------------------------------------------- stratified
def tab_stratified():
    with open(STRAT_FILE) as f:
        payload = json.load(f)
    rows = payload["results"]
    by_group = defaultdict(dict)
    labels = {}
    for r in rows:
        by_group[r["popgroup"]][r["epsilon"]] = r
        labels[r["popgroup"]] = _short_label(r["popgroup_label"])

    def _tabular_body(group_eps_pairs, include_internal=False):
        strata = [("populated cells", "mse_present"), ("empty cells", "mse_empty")]
        if include_internal:
            strata.append(("internal nodes", "mse_internal"))
        ncol = 3 * len(strata)
        body = [
            rf"\begin{{tabular}}{{ll{'r' * ncol}}}",
            r"\toprule",
            " & & " + " & ".join(rf"\multicolumn{{3}}{{c}}{{{name}}}"
                                 for name, _ in strata) + r" \\",
            "".join(rf"\cmidrule(lr){{{3 + 3*i}-{5 + 3*i}}}"
                    for i in range(len(strata))),
            r"Group & $\varepsilon$ & "
            + " & ".join(["Hay & Level & Node"] * len(strata)) + r" \\",
            r"\midrule",
        ]
        last_pg = None
        for pg, eps in group_eps_pairs:
            m = by_group[pg][eps]["methods"]
            head = labels[pg] if pg != last_pg else ""
            last_pg = pg
            cells = [fmt_mse(m[k][fld]) for _, fld in strata
                     for k in ("Hay", "Level", "Node")]
            body.append(rf"{head} & {eps:g} & " + " & ".join(cells) + r" \\")
        body += [r"\bottomrule", r"\end{tabular}"]
        return body

    def table(group_eps_pairs, stem, caption, label, star=False, placement="t",
              include_internal=False):
        env = "table*" if star else "table"
        lines = (["% Auto-generated by make_paper_assets.py -- do not edit by hand.",
                  rf"\begin{{{env}}}[{placement}]",
                  r"\centering\small",
                  rf"\caption{{{caption}}}",
                  rf"\label{{{label}}}"]
                 + _tabular_body(group_eps_pairs, include_internal)
                 + [rf"\end{{{env}}}"])
        with open(os.path.join(OUT_DIR, stem + ".tex"), "w") as f:
            f.write("\n".join(lines) + "\n")
        print(f"  wrote {stem}.tex")

    def table_nofloat(group_eps_pairs, stem, caption, label,
                      include_internal=False):
        """Non-floating variant: typeset exactly where \\input appears.
        Requires \\usepackage{capt-of} (or caption) in the preamble; intended
        for a one-column appendix page (\\clearpage\\onecolumn before it)."""
        lines = (["% Auto-generated by make_paper_assets.py -- do not edit by hand.",
                  "% NON-FLOATING variant: place after \\clearpage\\onecolumn;",
                  "% needs \\usepackage{capt-of} in the preamble.",
                  r"\begin{center}\small",
                  rf"\captionof{{table}}{{{caption}}}",
                  rf"\label{{{label}}}"]
                 + _tabular_body(group_eps_pairs, include_internal)
                 + [r"\end{center}"])
        with open(os.path.join(OUT_DIR, stem + ".tex"), "w") as f:
            f.write("\n".join(lines) + "\n")
        print(f"  wrote {stem}.tex")

    # single-column version: no Group column (group names become spanning
    # header rows), tighter column separation -- fits an ACM column.
    lines = [
        "% Auto-generated by make_paper_assets.py -- do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering\footnotesize",
        r"\setlength{\tabcolsep}{3.5pt}",
        r"\caption{Cell-type-stratified MSE on two Detailed DHC-A groups "
        r"(same draws as Table~\ref{tab:ddhca}). Level-wise trades the "
        r"populated cells for the empty ones; per-node cleans the empty "
        r"cells while staying near the unbiased baseline on the populated "
        r"ones.}",
        r"\label{tab:stratified}",
        r"\begin{tabular}{lrrrrrr}",
        r"\toprule",
        r" & \multicolumn{3}{c}{populated cells}"
        r" & \multicolumn{3}{c}{empty cells} \\",
        r"\cmidrule(lr){2-4}\cmidrule(lr){5-7}",
        r"$\varepsilon$ & Hay & Level & Node & Hay & Level & Node \\",
        r"\midrule",
    ]
    for pg in ("1190", "3657"):
        lines.append(rf"\multicolumn{{7}}{{l}}{{\emph{{{labels[pg]}}}}} \\")
        for eps in (0.1, 0.5, 1.0, 2.0):
            m = by_group[pg][eps]["methods"]
            cells = [fmt_mse(m[k]["mse_present"]) for k in ("Hay", "Level", "Node")]
            cells += [fmt_mse(m[k]["mse_empty"]) for k in ("Hay", "Level", "Node")]
            lines.append(rf"{eps:g} & " + " & ".join(cells) + r" \\")
        lines.append(r"\addlinespace[2pt]")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    with open(os.path.join(OUT_DIR, "tab_stratified_main.tex"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print("  wrote tab_stratified_main.tex")
    full_pairs = [(pg, e) for pg in ("1190", "1016", "2031", "3657", "1009")
                  for e in EPS_ORDER]
    # [!t]: the table is ~70% of the page height, above LaTeX's default
    # \dbltopfraction cap; the ! overrides the cap so it can sit on the
    # appendix page (pair with relaxed float fractions in the preamble).
    table(full_pairs, "tab_stratified_full",
          "Cell-type-stratified MSE, all Detailed DHC-A groups and privacy "
          "budgets (full version of Table~\\ref{tab:stratified}).",
          "tab:stratified-full", star=True, placement="!t",
          include_internal=True)
    # guaranteed-placement alternative for a one-column appendix page
    table_nofloat(full_pairs, "tab_stratified_full_nofloat",
                  "Cell-type-stratified MSE, all Detailed DHC-A groups and "
                  "privacy budgets (full version of "
                  "Table~\\ref{tab:stratified}).",
                  "tab:stratified-full", include_internal=True)


# -------------------------------------------------------------- diagnostic
def tab_diagnostic():
    with open(DIAG_FILE) as f:
        d = json.load(f)

    def row(name, ev):
        return (rf"{name} & {ev['n_decisive']}/{ev['n_configs']}"
                rf" & {100*ev['accuracy_decisive']:.1f}"
                rf" & {ev['mean_regret_pct']:.1f}"
                rf" & {ev['median_regret_pct']:.1f} \\")

    b = d["rule_b"]; a = d["rule_a"]
    lines = [
        "% Auto-generated by make_paper_assets.py -- do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering\small",
        r"\caption{Validation of the granularity diagnostic"
        rf" (Eq.~\ref{{eq:diagnostic}}, $\lambda={b['kappa']:g}$ tuned on the"
        r" balanced split only). Accuracy is over decisive configurations;"
        r" regret is MSE(chosen)/MSE(best)$-$1 over all configurations. The"
        rf" two-way variant ($\tau={a['tau']:g}$) cannot select"
        r" \textsc{scalar}, which costs it the unbalanced trees.}",
        r"\label{tab:diagnostic}",
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"Split & decisive & acc.\ (\%) & \multicolumn{2}{c}{regret (\%)} \\",
        r" & & & mean & median \\",
        r"\midrule",
        r"\multicolumn{5}{l}{\emph{Three-way penalized rule (ours)}} \\",
        row("~~balanced (tuning)", b["balanced"]),
        row("~~unbalanced (held out)", b["unbalanced_heldout"]),
        row("~~census DDHC-A (held out)", b["census_heldout"]),
        r"\addlinespace[2pt]",
        r"\multicolumn{5}{l}{\emph{Two-way rule (ablation)}} \\",
        row("~~balanced (tuning)", a["balanced"]),
        row("~~unbalanced (held out)", a["unbalanced_heldout"]),
        row("~~census DDHC-A (held out)", a["census_heldout"]),
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
    ]
    with open(os.path.join(OUT_DIR, "tab_diagnostic_validation.tex"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print("  wrote tab_diagnostic_validation.tex")


if __name__ == "__main__":
    os.makedirs(OUT_DIR, exist_ok=True)
    print(f"paper assets -> {OUT_DIR}")
    fig_synthetic()
    groups = _load_ddhca()
    fig_ddhca(groups)
    tab_ddhca(groups)
    tab_stratified()
    tab_diagnostic()
    print("done.")
