"""
Figures and LaTeX tables for the CCECE (IEEEtran) version of the paper.

Reads only archived results -- no experiment is re-run:
    ../results/synthetic_data_results/results_exactls.json   (runner.py --exact-ls --no-spectral)
    ../results/P1_sparse_results/p1_sparse_results.json      (P1_sparse_columns.py --exact-ls,
                                                              incl. the P1_001N control row)
    ../results/diagnostic_validation_exactls.json            (diagnostic_check.py --exact-ls --p1)
    ../census_data/census_hierarchy_format/P1_census_county_2020_<col>.json (E[c] per column)

Writes to ../results/ccece_assets/:
    fig_synthetic_strip.pdf/.png/.tex   Fig. 1: one row of four panels (one per signal
                                        class), improvement over projection vs eps, with
                                        +/-1 s.e. bands over the 18 configurations per point
    fig_p1_crossover.pdf/.png/.tex      Fig. 2: the six P1 columns, Level vs Node vs eps
    tab_p1_improvement.tex              Table I (single-column float): improvement over
                                        projection (%), Level/Node rows per column + control
    tab_p1_stratified.tex               Table II: populated- vs empty-cell MSE, selected rows
    tab_p1_stratified_full.tex          all columns x all eps (arXiv version)
    tab_diagnostic_ccece.tex            Table III: diagnostic validation
and prints the numbers the text cites (crossover budgets, pitfall rows, SEs).

Run from core/:  python make_ccece_assets.py
The .tex files use booktabs; captions go ABOVE tables (IEEE style).
"""
from __future__ import annotations
import json
import os
from collections import defaultdict

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

SYN_FILE = "../results/synthetic_data_results/results_exactls.json"
P1_FILE = "../results/P1_sparse_results/p1_sparse_results.json"
DIAG_FILE = "../results/diagnostic_validation_exactls.json"
HIER_DIR = "../census_data/census_hierarchy_format"
OUT_DIR = "../results/ccece_assets"

CONTROL = "P1_001N"
EPS_ORDER = [0.01, 0.1, 0.5, 1.0, 2.0, 5.0, 10.0]
SIGNAL_ORDER = ["uniform", "smooth", "random", "sparse"]
GRANS = [("Scalar", "Scalar", "#009E73", ":"),
         ("Ours", "Level", "#0072B2", "-"),
         ("PerNode", "Node", "#D55E00", "--")]
P1_GRANS = [("Scalar", "Scalar", "#009E73", ":"),
            ("Level", "Level", "#0072B2", "-"),
            ("Node", "Node", "#D55E00", "--")]
# Table II rows: (column, eps) pairs that show the three regimes; edit freely.
STRAT_ROWS = [("P1_060N", 0.5), ("P1_060N", 5.0), ("P1_068N", 0.5), ("P1_068N", 1.0),
              ("P1_044N", 0.5), ("P1_043N", 0.5)]

plt.rcParams.update({
    "font.size": 8, "axes.titlesize": 8, "axes.labelsize": 8,
    "legend.fontsize": 7, "xtick.labelsize": 7, "ytick.labelsize": 7,
    "figure.dpi": 110, "savefig.bbox": "tight",
})


# ------------------------------------------------------------------ helpers
def _save(fig, stem):
    for ext in ("pdf", "png"):
        fig.savefig(os.path.join(OUT_DIR, f"{stem}.{ext}"), dpi=220 if ext == "png" else None)
    plt.close(fig)
    print(f"  wrote {stem}.pdf/.png")


def _write(stem, lines):
    with open(os.path.join(OUT_DIR, stem), "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  wrote {stem}")


def fmt_pct(v):
    return "0.0" if abs(v) < 0.05 else f"{v:.1f}"


def fmt_mse(v):
    if v >= 1000:
        return f"{v:,.0f}"
    if v >= 10:
        return f"{v:.1f}"
    return f"{v:.2f}"


def short_name(col):
    return col.replace("P1_", "P1\\_")


def column_ec(col, eps=0.5):
    """Expected leaf-level coefficient E[c] = ||x||^2 / (||x||^2 + n sigma^2)."""
    with open(os.path.join(HIER_DIR, f"P1_census_county_2020_{col}.json")) as f:
        rec = json.load(f)
    levels = np.array(rec["levels"])
    x = np.array(rec["x"])[levels == levels.max()]
    s2 = 2.0 * (rec["sensitivity"] / eps) ** 2
    ssq = float((x ** 2).sum())
    return ssq / (ssq + len(x) * s2), float(np.mean(x == 0)), int(x.max()), rec["label"]


def _fig_tex(stem, caption, label, star=True):
    env = "figure*" if star else "figure"
    width = r"\textwidth" if star else r"\columnwidth"
    _write(stem + ".tex", [
        "% Auto-generated by make_ccece_assets.py -- do not edit by hand.",
        rf"\begin{{{env}}}[t]", r"\centering",
        rf"\includegraphics[width={width}]{{{stem}.pdf}}",
        rf"\caption{{{caption}}}", rf"\label{{{label}}}", rf"\end{{{env}}}"])


# ------------------------------------------------------------- Fig. 1 strip
def fig_synthetic_strip():
    with open(SYN_FILE) as f:
        payload = json.load(f)
    agg = defaultdict(list)
    for r in payload["results"]:
        for key, *_ in GRANS:
            agg[(r["signal_type"], r["epsilon"], key)].append(
                r["methods"][key]["improve_over_hay_pct"])
    fig, axes = plt.subplots(1, 4, figsize=(7.16, 1.9), sharey=True)
    for ax, st in zip(axes, SIGNAL_ORDER):
        for key, label, color, ls in GRANS:
            ys = np.array([agg[(st, e, key)] for e in EPS_ORDER])       # (7, 18)
            m = ys.mean(axis=1)
            se = ys.std(axis=1, ddof=1) / np.sqrt(ys.shape[1])
            ax.plot(EPS_ORDER, m, ls, color=color, marker="o", ms=2.5, lw=1.1, label=label)
            ax.fill_between(EPS_ORDER, m - se, m + se, color=color, alpha=0.18, lw=0)
        ax.axhline(0, color="0.6", lw=0.7)
        ax.set_xscale("log")
        ax.set_title(f"{st} signals")
        ax.set_ylim(-15, 100)
        ax.set_xlabel(r"privacy budget $\varepsilon$")
        ax.grid(True, which="both", alpha=0.25, lw=0.4)
    axes[0].set_ylabel("improvement over\nprojection (%)")
    axes[0].legend(loc="lower left", frameon=False)
    fig.tight_layout(w_pad=0.6)
    _save(fig, "fig_synthetic_strip")
    _fig_tex("fig_synthetic_strip",
             r"Improvement in per-cell MSE over consistency projection versus privacy "
             r"budget, by signal class (mean over 9 trees $\times$ 2 scales, 50 draws per "
             r"configuration; bands are $\pm 1$ standard error of the mean over the 18 "
             r"configurations). Level-wise shrinkage dominates on dense, homogeneous "
             r"signals; per-node overtakes on sparse and random signals as $\varepsilon$ grows.",
             "fig:synthetic")
    return payload


# --------------------------------------------------------- Fig. 2 crossover
def fig_p1_crossover(rows, cols):
    fig, axes = plt.subplots(2, 3, figsize=(7.16, 3.6), sharex=True, sharey=True)
    for ax, col in zip(axes.flat, cols):
        ec, zf, mx, lab = column_ec(col)
        per_eps = {r["epsilon"]: r["methods"] for r in rows if r["column"] == col}
        for key, label, color, ls in P1_GRANS:
            y = [per_eps[e][key]["improve_over_hay_pct"] for e in EPS_ORDER]
            ax.plot(EPS_ORDER, y, ls, color=color, marker="o", ms=2.5, lw=1.1, label=label)
        ax.axhline(0, color="0.6", lw=0.7)
        ax.set_xscale("log")
        ax.set_ylim(-5, 102)
        ax.set_title(rf"{col.replace('_', ' ')}: $E[c]={ec:.2f}$, {100*zf:.0f}% zero", fontsize=7.5)
        ax.grid(True, which="both", alpha=0.25, lw=0.4)
    for ax in axes[1]:
        ax.set_xlabel(r"privacy budget $\varepsilon$")
    for ax in axes[:, 0]:
        ax.set_ylabel("improvement over\nprojection (%)")
    axes[0, 0].legend(loc="lower left", frameon=False)
    fig.tight_layout(w_pad=0.6, h_pad=0.5)
    _save(fig, "fig_p1_crossover")
    _fig_tex("fig_p1_crossover",
             r"Six sparse county-level columns of the 2020 Census P1 table, ordered by the "
             r"expected leaf-level coefficient $E[c]$ at $\varepsilon=0.5$ (50 draws per "
             r"point). The budget at which per-node overtakes level-wise falls as $E[c]$ rises.",
             "fig:p1")


# ---------------------------------------------------------------- Table I
def tab_p1_improvement(rows, cols):
    max_se = max(r["methods"][m]["imp_se"] for r in rows for m in ("Level", "Node"))
    lines = [
        "% Auto-generated by make_ccece_assets.py -- do not edit by hand.",
        r"\begin{table}[t]",
        r"\caption{Improvement in per-cell MSE over consistency projection (\%) on six "
        r"sparse county-level columns of the 2020 Census P1 table (multi-race combinations, "
        r"ordered by the expected leaf-level coefficient $E[c]$ at $\varepsilon=0.5$) and on "
        r"the total-population control. Every county is published, zeros included. Standard "
        rf"errors of the paired per-draw improvement are below {max_se:.1f} points throughout; "
        r"the scalar granularity is dominated in every cell and is omitted.}",
        r"\label{tab:p1}",
        r"\centering\footnotesize",
        r"\setlength{\tabcolsep}{2.3pt}",
        r"\begin{tabular}{ll" + "r" * len(EPS_ORDER) + "}",
        r"\toprule",
        r"Column ($E[c]$) & Gran. & " +
        " & ".join(rf"$\varepsilon{{=}}{e:g}$" for e in EPS_ORDER) + r" \\",
        r"\midrule",
    ]
    for col in cols:
        ec, zf, mx, lab = column_ec(col)
        per_eps = {r["epsilon"]: r["methods"] for r in rows if r["column"] == col}
        for i, (key, disp, *_) in enumerate(P1_GRANS[1:]):
            vals = " & ".join(fmt_pct(per_eps[e][key]["improve_over_hay_pct"]) for e in EPS_ORDER)
            head = rf"{short_name(col)} ({ec:.2f})" if i == 0 else ""
            lines.append(rf"{head} & {disp} & {vals} \\")
        lines.append(r"\addlinespace[1pt]")
    per_eps = {r["epsilon"]: r["methods"] for r in rows if r["column"] == CONTROL}
    if per_eps:
        ec, *_ = column_ec(CONTROL)
        for i, (key, disp, *_) in enumerate(P1_GRANS[1:]):
            vals = " & ".join(fmt_pct(per_eps[e][key]["improve_over_hay_pct"]) for e in EPS_ORDER)
            head = rf"Total pop.\ ({ec:.2f})" if i == 0 else ""
            lines.append(rf"{head} & {disp} & {vals} \\")
    else:
        print(f"  !! {CONTROL} not in the P1 results; control row omitted "
              f"(run: python P1_sparse_columns.py --columns {CONTROL} --exact-ls)")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    _write("tab_p1_improvement.tex", lines)


# --------------------------------------------------------------- Table II
def _strat_body(rows, pairs):
    body = []
    for col, eps in pairs:
        r = next((r for r in rows if r["column"] == col and r["epsilon"] == eps), None)
        if r is None:
            continue
        b = r["methods"]
        body.append(
            rf"{short_name(col)} & {eps:g} & "
            rf"{fmt_mse(b['Hay']['mse_present'])} & {fmt_mse(b['Level']['mse_present'])} & "
            rf"{fmt_mse(b['Node']['mse_present'])} & "
            rf"{fmt_mse(b['Hay']['mse_empty'])} & {fmt_mse(b['Level']['mse_empty'])} & "
            rf"{fmt_mse(b['Node']['mse_empty'])} & "
            rf"{fmt_pct(b['Level']['improve_over_hay_pct'])} & "
            rf"{fmt_pct(b['Node']['improve_over_hay_pct'])} \\")
    return body


def tab_p1_stratified(rows, cols):
    header = [
        r"\begin{tabular}{lrrrrrrrrr}",
        r"\toprule",
        r" & & \multicolumn{3}{c}{populated leaves} & \multicolumn{3}{c}{empty leaves} & "
        r"\multicolumn{2}{c}{aggregate impr.\ (\%)} \\",
        r"\cmidrule(lr){3-5}\cmidrule(lr){6-8}\cmidrule(lr){9-10}",
        r"Column & $\varepsilon$ & Proj. & Level & Node & Proj. & Level & Node & Level & Node \\",
        r"\midrule",
    ]
    cap = (r"Per-cell MSE by cell type on the P1 columns: populated leaves (county count "
           r"$> 0$) versus empty leaves, for consistency projection alone (Proj.), level-wise "
           r"and per-node shrinkage, with the aggregate improvement over projection. "
           r"Level-wise can cut aggregate error sharply while raising the error on the "
           r"populated cells; per-node lowers both until the counts exceed the noise.")
    _write("tab_p1_stratified.tex",
           ["% Auto-generated by make_ccece_assets.py -- do not edit by hand.",
            r"\begin{table}[t]", rf"\caption{{{cap}}}", r"\label{tab:stratified}",
            r"\centering\footnotesize", r"\setlength{\tabcolsep}{2.6pt}"]
           + header + _strat_body(rows, STRAT_ROWS)
           + [r"\bottomrule", r"\end{tabular}", r"\end{table}"])
    pairs = [(c, e) for c in cols for e in EPS_ORDER]
    _write("tab_p1_stratified_full.tex",
           ["% Auto-generated by make_ccece_assets.py -- do not edit by hand.",
            r"\begin{table*}[t]",
            r"\caption{Cell-type-stratified per-cell MSE on all six P1 columns and all "
            r"privacy budgets (full version of Table~\ref{tab:stratified}).}",
            r"\label{tab:stratified-full}", r"\centering\footnotesize",
            r"\setlength{\tabcolsep}{3.5pt}"]
           + header + _strat_body(rows, pairs)
           + [r"\bottomrule", r"\end{tabular}", r"\end{table*}"])


# -------------------------------------------------------------- Table III
def tab_diagnostic():
    with open(DIAG_FILE) as f:
        d = json.load(f)

    def row(name, ev):
        return (rf"{name} & {ev['n_decisive']}/{ev['n_configs']}"
                rf" & {100*ev['accuracy_decisive']:.1f}"
                rf" & {ev['mean_regret_pct']:.1f} & {ev['median_regret_pct']:.1f} \\")

    b, a = d["rule_b"], d["rule_a"]
    census = "census P1 (held out)"
    _write("tab_diagnostic_ccece.tex", [
        "% Auto-generated by make_ccece_assets.py -- do not edit by hand.",
        r"\begin{table}[t]",
        r"\caption{Validation of the granularity diagnostic "
        rf"(Eq.~\ref{{eq:diagnostic}}, $\lambda={b['kappa']:g}$ tuned on the balanced "
        r"split only). Accuracy is over decisive configurations; regret is "
        r"MSE(chosen)/MSE(best)$-$1 over all configurations. The two-way variant "
        rf"($\tau={a['tau']:g}$) cannot select \textsc{{scalar}}.}}",
        r"\label{tab:diagnostic}",
        r"\centering\small",
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"Split & decisive & acc.\ (\%) & \multicolumn{2}{c}{regret (\%)} \\",
        r" & & & mean & median \\",
        r"\midrule",
        r"\multicolumn{5}{l}{\emph{Three-way penalized rule (ours)}} \\",
        row("~~balanced (tuning)", b["balanced"]),
        row("~~unbalanced (held out)", b["unbalanced_heldout"]),
        row("~~" + census, b["census_heldout"]),
        r"\addlinespace[2pt]",
        r"\multicolumn{5}{l}{\emph{Two-way rule (ablation)}} \\",
        row("~~balanced (tuning)", a["balanced"]),
        row("~~unbalanced (held out)", a["unbalanced_heldout"]),
        row("~~" + census, a["census_heldout"]),
        r"\bottomrule", r"\end{tabular}", r"\end{table}"])
    return d


# -------------------------------------------------------- numbers to cite
def print_numbers(syn, rows, cols, diag):
    R = syn["results"]
    imp = lambda r, m: r["methods"][m]["improve_over_hay_pct"]
    dense = [r for r in R if r["signal_type"] in ("uniform", "smooth")]
    print("\n=== NUMBERS THE TEXT CITES ===")
    print(f"synthetic: {len(R)} configs; level beats node on dense/homogeneous signals in "
          f"{sum(r['methods']['Ours']['mse_mean'] < r['methods']['PerNode']['mse_mean'] for r in dense)}"
          f" of {len(dense)}")
    print("  full-grid mean Level improvement by eps: " +
          ", ".join(f"{e:g}: {np.mean([imp(r, 'Ours') for r in R if r['epsilon'] == e]):.1f}%"
                    for e in EPS_ORDER))
    print("  full-grid means: " + ", ".join(
        f"{d}: {np.mean([imp(r, k) for r in R]):.1f}%" for k, d, *_ in GRANS))
    rel = [(r["methods"][m]["mse_std"] / np.sqrt(r["num_trials"])) / r["methods"][m]["mse_mean"]
           for r in R for m in ("Hay", "Ours", "PerNode", "Scalar") if r["methods"][m]["mse_mean"] > 0]
    print(f"  per-config SE/mean: median {100*np.median(rel):.1f}%, 90th pct {100*np.percentile(rel, 90):.1f}%")
    print("\nP1 columns (E[c]@0.5, zero fraction, max count, crossover budget):")
    for col in cols:
        ec, zf, mx, lab = column_ec(col)
        per_eps = {r["epsilon"]: r["methods"] for r in rows if r["column"] == col}
        win = ["L" if per_eps[e]["Level"]["improve_over_hay_pct"] >= per_eps[e]["Node"]["improve_over_hay_pct"]
               else "N" for e in EPS_ORDER]
        cross = next((f"between {EPS_ORDER[i-1]:g} and {EPS_ORDER[i]:g}" for i in range(1, len(win))
                      if win[i-1] == "L" and win[i] == "N"), "none (Level wins throughout)" if "N" not in win
                     else "Node from eps=0.01")
        worst = max(EPS_ORDER, key=lambda e: per_eps[e]["Level"]["mse_present"] / per_eps[e]["Hay"]["mse_present"])
        b = per_eps[worst]
        print(f"  {col}: E[c]={ec:.3f} zero={100*zf:.1f}% max={mx} | Level->Node crossover {cross}"
              f" | worst populated-cell inflation of Level: x{b['Level']['mse_present']/b['Hay']['mse_present']:.2f}"
              f" at eps={worst:g} (aggregate impr. {b['Level']['improve_over_hay_pct']:.1f}%)")
    mx_se = max(r["methods"][m]["imp_se"] for r in rows for m in ("Level", "Node"))
    print(f"  max paired SE in Table I: {mx_se:.2f} points")
    b = diag["rule_b"]
    print("\ndiagnostic: " + "; ".join(
        f"{k}: {100*v['accuracy_decisive']:.1f}% on {v['n_decisive']}/{v['n_configs']} "
        f"(regret mean {v['mean_regret_pct']:.1f}%, median {v['median_regret_pct']:.1f}%)"
        for k, v in [("balanced", b["balanced"]), ("unbalanced", b["unbalanced_heldout"]),
                     ("census P1", b["census_heldout"])]))
    sd = diag["single_draw"]
    print("  single-draw accuracy: " + ", ".join(f"{k} {100*v['accuracy_single_draw']:.1f}%" for k, v in sd.items()))
    ng = diag["nogain"]
    print(f"  no-gain flag: synthetic recall {ng['synthetic']['recall']:.3f} "
          f"({round(ng['synthetic']['recall']*ng['synthetic']['n_nogain_true'])}/{ng['synthetic']['n_nogain_true']}),"
          f" precision {ng['synthetic']['precision']:.2f}; census: {ng['census']['n_nogain_pred']} flagged, "
          f"{ng['census']['n_nogain_true']} true (the control rows)")


if __name__ == "__main__":
    os.makedirs(OUT_DIR, exist_ok=True)
    print(f"CCECE assets -> {OUT_DIR}")
    with open(P1_FILE) as f:
        p1 = json.load(f)
    rows = p1["results"]
    cols = [c for c in p1["config"]["columns"] if c != CONTROL]
    cols.sort(key=lambda c: column_ec(c)[0])
    syn = fig_synthetic_strip()
    fig_p1_crossover(rows, cols)
    tab_p1_improvement(rows, cols)
    tab_p1_stratified(rows, cols)
    diag = tab_diagnostic()
    print_numbers(syn, rows, cols, diag)
    print("done.")
