"""
run_ccece.py -- one command for the conference (CCECE) pipeline.

Runs, in order, from the archived synthetic DP draws and the PL94 P1 CSV:

  1  runner.py --exact-ls --no-spectral      synthetic grid, exact LS projection
  2  P1_sparse_columns.py --exact-ls         six sparse P1 columns + the P1_001N control
  3  diagnostic_check.py --exact-ls --p1     granularity diagnostic, P1 as the held-out set
  4  make_ccece_assets.py                    IEEE tables/figures + the numbers the text cites

Optional:
  --fresh         delete the derived CCECE result files first, so nothing stale
                  (e.g. a P1 column no longer in the set) survives into the tables
  --verify        first re-check the tree / signal / noise archives against the
                  generators (golden-master checks; several minutes)
  --sensitivity   afterwards run the DDHC-A absent-county sensitivity (arXiv version)
  --from N        resume at main step N (1-4)
  --list          print the steps and exit

Usage, from anywhere:   python core/run_ccece.py --fresh
Stops at the first failing step and prints that step's command so it can be
re-run alone. Everything printed is also written to results/ccece_run_log.txt.
"""
from __future__ import annotations
import datetime
import os
import shutil
import subprocess
import sys
import time

CORE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(CORE)
RESULTS = os.path.join(ROOT, "results")
LOG_FILE = os.path.join(RESULTS, "ccece_run_log.txt")

sys.path.insert(0, CORE)
try:
    from P1_sparse_columns import DEFAULT_COLUMNS as P1_COLUMNS
except Exception:                                   # keep in sync with P1_sparse_columns.py
    P1_COLUMNS = ["P1_060N", "P1_058N", "P1_068N", "P1_044N", "P1_043N", "P1_057N"]
CONTROL = "P1_001N"

MAIN = [
    ("synthetic grid, exact LS projection, no spectral",
     ["runner.py", "--exact-ls", "--no-spectral"]),
    ("PL94 P1 sparse columns + total-population control, exact LS",
     ["P1_sparse_columns.py", "--exact-ls", "--columns", *P1_COLUMNS, CONTROL]),
    ("granularity diagnostic, P1 columns as the held-out set",
     ["diagnostic_check.py", "--exact-ls", "--p1"]),
    ("IEEE tables and figures + numbers the text cites",
     ["make_ccece_assets.py"]),
]
VERIFY = [
    ("check tree archives against the generator", ["hierarchy_data_generator.py"]),
    ("check signal archives against the generator", ["signal_generator.py"]),
    ("check DP noise archives against the generator", ["laplace_noise_injection.py"]),
]
SENSITIVITY = [
    ("DDHC-A absent-county sensitivity (arXiv version)", ["sensitivity_absent_counties.py"]),
]
# derived files removed by --fresh (all regenerated by the run)
DERIVED = [
    "synthetic_data_results/results_exactls.json",
    "P1_sparse_results/p1_sparse_results.json",
    "diagnostic_validation_exactls.json",
    "diagnostic_sensitivity_exactls.json",
    "ccece_assets",
]
OUTPUTS = [
    "synthetic_data_results/results_exactls.json",
    "P1_sparse_results/p1_sparse_results.json",
    "diagnostic_validation_exactls.json",
    "diagnostic_sensitivity_exactls.json",
    "ccece_assets",
]


def _echo(logf, text: str) -> None:
    sys.stdout.write(text)
    sys.stdout.flush()
    logf.write(text)
    logf.flush()


def run_step(tag: str, name: str, cmd: list, logf) -> None:
    _echo(logf, f"\n[{tag}] {name}\n    $ python {' '.join(cmd)}\n")
    env = dict(os.environ, PYTHONUNBUFFERED="1", PYTHONIOENCODING="utf-8", PYTHONUTF8="1")
    t0 = time.time()
    with subprocess.Popen([sys.executable, *cmd], cwd=CORE, env=env, text=True,
                          encoding="utf-8", errors="replace", bufsize=1,
                          stdout=subprocess.PIPE, stderr=subprocess.STDOUT) as p:
        for line in p.stdout:
            _echo(logf, "    " + line)
        rc = p.wait()
    dt = time.time() - t0
    status = "ok" if rc == 0 else f"FAILED (exit {rc})"
    _echo(logf, f"[{tag}] {status} in {dt:.0f}s\n")
    if rc != 0:
        _echo(logf, f"\nStopped. Re-run this step alone with:\n    cd core\n    python {' '.join(cmd)}\n")
        sys.exit(rc)


def list_steps() -> None:
    print("Steps run by run_ccece.py (from core/):")
    for tag, (name, cmd) in [("V1", VERIFY[0]), ("V2", VERIFY[1]), ("V3", VERIFY[2])]:
        print(f"  {tag:>2}  [--verify]       python {' '.join(cmd)}")
    for i, (name, cmd) in enumerate(MAIN, 1):
        print(f"  {i:>2}                   python {' '.join(cmd)}")
    for name, cmd in SENSITIVITY:
        print(f"  S1  [--sensitivity]  python {' '.join(cmd)}")


def main(argv: list) -> None:
    if "--list" in argv:
        list_steps()
        return
    start = 1
    if "--from" in argv:
        start = int(argv[argv.index("--from") + 1])
    os.makedirs(RESULTS, exist_ok=True)
    if "--fresh" in argv and start == 1:
        for rel in DERIVED:
            path = os.path.join(RESULTS, rel)
            if os.path.isdir(path):
                shutil.rmtree(path)
            elif os.path.exists(path):
                os.remove(path)
    with open(LOG_FILE, "a", encoding="utf-8") as logf:
        try:
            commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT,
                                    capture_output=True, text=True).stdout.strip() or "n/a"
        except Exception:
            commit = "n/a"
        _echo(logf, f"\n{'=' * 78}\nCCECE pipeline  {datetime.datetime.now():%Y-%m-%d %H:%M}  "
                    f"python {sys.version.split()[0]}  commit {commit}  args {' '.join(argv) or '(none)'}\n"
                    f"{'=' * 78}\n")
        t_all = time.time()
        if "--verify" in argv and start == 1:
            for i, (name, cmd) in enumerate(VERIFY, 1):
                run_step(f"V{i}", name, cmd, logf)
        for i, (name, cmd) in enumerate(MAIN, 1):
            if i >= start:
                run_step(str(i), name, cmd, logf)
        if "--sensitivity" in argv:
            for name, cmd in SENSITIVITY:
                run_step("S1", name, cmd, logf)
        _echo(logf, f"\nAll steps finished in {time.time() - t_all:.0f}s. Outputs:\n")
        for rel in OUTPUTS:
            path = os.path.join(RESULTS, rel)
            if os.path.isdir(path):
                names = sorted(os.listdir(path))
                _echo(logf, f"  results/{rel}/  ({len(names)} files: {', '.join(names)})\n")
            elif os.path.exists(path):
                mtime = datetime.datetime.fromtimestamp(os.path.getmtime(path))
                _echo(logf, f"  results/{rel}  ({os.path.getsize(path):,} bytes, {mtime:%Y-%m-%d %H:%M})\n")
            else:
                _echo(logf, f"  results/{rel}  (missing)\n")
        _echo(logf, f"  log: results/{os.path.basename(LOG_FILE)}\n")


if __name__ == "__main__":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
    main(sys.argv[1:])
